/**
 * CATÁLOGO DE ERROS CONHECIDOS (decisão R8 do Framework de Mensagens,
 * Alertas e Validação — prompt_framework_mensagens_validacao.md,
 * Valdo 2026-07-19). FONTE DA VERDADE: este arquivo — o código do erro
 * nasce no MESMO commit do throw que o dispara (impossível dessincronizar).
 * A tabela de referência setes_central.tb_error_catalog é DERIVADA daqui
 * por `npm run errors:gen` (nunca editada à mão) para permitir joins SQL
 * com a tb_crashlytics ("quantos ORDER_INVOICED esse mês?").
 *
 * Uso: `throw new HttpError(409, msg, fields, ErrorCodes.ORDER_INVOICED)`.
 * O envelope de erro vira `{ error, code?, ref?, fields? }`.
 */

export const ErrorCodes = {
  // Infra/contrato
  INTERNAL:            'INTERNAL',
  VALIDATION_FAILED:   'VALIDATION_FAILED',
  INVALID_ID:          'INVALID_ID',
  REQUIRED_FIELDS:     'REQUIRED_FIELDS',
  CONFLICT_RETRY:      'CONFLICT_RETRY',
  NOT_FOUND:           'NOT_FOUND',
  // Cadastros / cadeia fiscal
  DUP_DOCUMENT:        'DUP_DOCUMENT',
  DUP_ROLE:            'DUP_ROLE',
  ROLE_MISSING:        'ROLE_MISSING',
  // Árvores (categories/financial-plans)
  PARENT_NOT_FOUND:    'PARENT_NOT_FOUND',
  HAS_CHILDREN:        'HAS_CHILDREN',
  TREE_CYCLE:          'TREE_CYCLE',
  // Software House — ciclo de serviços
  ORDER_OPEN_EXISTS:   'ORDER_OPEN_EXISTS',
  ORDER_INVOICED:      'ORDER_INVOICED',
  ORDER_NO_ITEMS:      'ORDER_NO_ITEMS',
  PAYMENT_TYPE_UNAVAILABLE: 'PAYMENT_TYPE_UNAVAILABLE',
  // Financeiro
  TITLE_NOT_FOUND:     'TITLE_NOT_FOUND',
  BANK_NOT_FOUND:      'BANK_NOT_FOUND',
  BANK_IN_USE:         'BANK_IN_USE',
  // Contrato financeiro (migration 038) e boleto (migration 039)
  FINANCIAL_CONTRACT_EXISTS:        'FINANCIAL_CONTRACT_EXISTS',
  FINANCIAL_CONTRACT_CASH_NO_TERMS: 'FINANCIAL_CONTRACT_CASH_NO_TERMS',
  PAYMENT_TYPE_NOT_LINKED:          'PAYMENT_TYPE_NOT_LINKED',
  AGREEMENT_NOT_FOUND:              'AGREEMENT_NOT_FOUND',
  AGREEMENT_INACTIVE:               'AGREEMENT_INACTIVE',
  TITLE_NOT_RECEIVABLE:             'TITLE_NOT_RECEIVABLE',
  TITLE_SETTLED:                    'TITLE_SETTLED',
  TITLE_HAS_OPEN_SLIP:              'TITLE_HAS_OPEN_SLIP',
  BANK_SLIP_NOT_FOUND:              'BANK_SLIP_NOT_FOUND',
  BANK_SLIP_NO_TITLES:              'BANK_SLIP_NO_TITLES',
  BANK_SLIP_DUPLICATE_TITLE:        'BANK_SLIP_DUPLICATE_TITLE',
  BANK_SLIP_MIXED_CUSTOMERS:        'BANK_SLIP_MIXED_CUSTOMERS',
  BANK_SLIP_EXPIRATION_REQUIRED:    'BANK_SLIP_EXPIRATION_REQUIRED',
  BANK_SLIP_INVALID_VALUE:          'BANK_SLIP_INVALID_VALUE',
  BANK_SLIP_NOT_OPEN:               'BANK_SLIP_NOT_OPEN',
  BANK_SLIP_NOT_SETTLED:            'BANK_SLIP_NOT_SETTLED',
  BANK_SLIP_TITLE_REISSUED:         'BANK_SLIP_TITLE_REISSUED',
  BANK_SLIP_BELOW_MINIMUM:          'BANK_SLIP_BELOW_MINIMUM',
  // Contrato/boleto: gates graciosos que também podem bloquear operações manuais
  NO_OPEN_CASHIER:                  'NO_OPEN_CASHIER',
  BANK_ACCOUNT_REQUIRED:            'BANK_ACCOUNT_REQUIRED',
  // Cheque (migration 040)
  CHECK_REQUIRED:                   'CHECK_REQUIRED',
  CHECK_SUM_MISMATCH:               'CHECK_SUM_MISMATCH',
  CHECK_NOT_FOUND:                  'CHECK_NOT_FOUND',
  CHECK_ALREADY_ACTIVE:             'CHECK_ALREADY_ACTIVE',
  CHECK_NOT_IN_CUSTODY:             'CHECK_NOT_IN_CUSTODY',
  CHECK_NOT_DISCOUNTED:             'CHECK_NOT_DISCOUNTED',
  CHECK_NOT_RETURNABLE:             'CHECK_NOT_RETURNABLE',
  CHECK_NO_ORIGIN:                  'CHECK_NO_ORIGIN',
  CHECK_ALREADY_MOVED:              'CHECK_ALREADY_MOVED',
  CHECK_EVENT_NOT_FOUND:            'CHECK_EVENT_NOT_FOUND',
  CHECK_EVENT_NOT_REVERSIBLE:       'CHECK_EVENT_NOT_REVERSIBLE',
  CHECK_EXCEEDS_BALANCE:            'CHECK_EXCEEDS_BALANCE',
  CHECK_FACTORING_NOT_FOUND:        'CHECK_FACTORING_NOT_FOUND',
  CHECK_IDENTITY_MISMATCH:          'CHECK_IDENTITY_MISMATCH',
  REVERSAL_NOT_CURRENT: 'REVERSAL_NOT_CURRENT',
  // Parcerias
  RATE_SUM_EXCEEDED:   'RATE_SUM_EXCEEDED',
  // Faturamento (billing — W2 Onda 3)
  REQUIRES_VALIDATION: 'REQUIRES_VALIDATION',
  ORDER_NO_BRANCH:     'ORDER_NO_BRANCH',
  ORDER_NO_BILLING:    'ORDER_NO_BILLING',
  // Transporte (handler global — gate adversarial 2026-09-06): body inválido é erro do cliente
  INVALID_JSON:        'INVALID_JSON',
  PAYLOAD_TOO_LARGE:   'PAYLOAD_TOO_LARGE',
  // Negociação do pedido (prompt_negociacao_pedido.md)
  ORDER_NOT_FOUND:     'ORDER_NOT_FOUND',
  INSTALLMENT_INVALID: 'INSTALLMENT_INVALID',
  MAX_PARCELS_EXCEEDED: 'MAX_PARCELS_EXCEEDED',
  ADJUST_PARAMS_REQUIRED: 'ADJUST_PARAMS_REQUIRED',
  INVALID_DEADLINE:    'INVALID_DEADLINE',
  NEGATIVE_ITEM_VALUE: 'NEGATIVE_ITEM_VALUE',
  MISSING_NCM:         'MISSING_NCM',
  INSTALLMENT_MISMATCH: 'INSTALLMENT_MISMATCH',
  // Devolução de mercadoria (order-returns, 2026-08-24)
  RETURN_INVALID:      'RETURN_INVALID',
  RETURN_REQUIRES_ENTRY: 'RETURN_REQUIRES_ENTRY',
  ORIGIN_NOT_INVOICED: 'ORIGIN_NOT_INVOICED',
  NOTHING_RETURNABLE:  'NOTHING_RETURNABLE',
  // Cancelamento de nota (prompt_cancelamento_nota.md, 2026-09-08)
  INVOICE_NOT_FOUND:   'INVOICE_NOT_FOUND',
  INVOICE_NOT_CANCELLABLE: 'INVOICE_NOT_CANCELLABLE',
  INVOICE_REASON_REQUIRED: 'INVOICE_REASON_REQUIRED',
  INVOICE_CANCEL_BLOCKED: 'INVOICE_CANCEL_BLOCKED',
  PRIVILEGE_REQUIRED:  'PRIVILEGE_REQUIRED',
  RESOURCE_BUSY:       'RESOURCE_BUSY',
  TITLE_EXCEEDS_BALANCE: 'TITLE_EXCEEDS_BALANCE',
  SERVICE_ORDER_CUSTOMER_OPEN: 'SERVICE_ORDER_CUSTOMER_OPEN',
  SERVICE_ORDER_OWN_ENDPOINT: 'SERVICE_ORDER_OWN_ENDPOINT',
  SERVICE_ORDER_ITEM_NOT_SERVICE: 'SERVICE_ORDER_ITEM_NOT_SERVICE',
  SERVICE_ORDER_ITEM_VALUE_REQUIRED: 'SERVICE_ORDER_ITEM_VALUE_REQUIRED',
} as const

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes]

/** Descrições p/ a tabela derivada (errors:gen) e docs — PT (produto). */
export const ErrorCatalog: Record<ErrorCode, string> = {
  INTERNAL:            'Erro interno do servidor (rastreável pelo ref na tb_crashlytics)',
  VALIDATION_FAILED:   'Payload rejeitado pela validação de formato (Zod) — fields[] aponta os campos',
  INVALID_ID:          'Identificador de rota inválido',
  REQUIRED_FIELDS:     'Campos obrigatórios (configuração do cliente) não preenchidos',
  CONFLICT_RETRY:      'Corrida de cadastro simultâneo detectada — tentar novamente',
  NOT_FOUND:           'Registro não encontrado no escopo do usuário',
  DUP_DOCUMENT:        'CPF/CNPJ/schema já cadastrado em outro registro',
  DUP_ROLE:            'A entidade já tem este papel nesta institution (fields[0] = id existente)',
  ROLE_MISSING:        'Entidade sem o papel necessário nesta institution',
  PARENT_NOT_FOUND:    'Nível superior inexistente na árvore',
  HAS_CHILDREN:        'Registro tem subníveis vivos — exclusão bloqueada',
  TREE_CYCLE:          'Movimento criaria ciclo na árvore',
  ORDER_OPEN_EXISTS:   'Cliente já tem ordem de serviço aberta (D5 — máx. 1)',
  ORDER_INVOICED:      'Ordem já faturada — alterações só via financeiro',
  ORDER_NO_ITEMS:      'Ordem sem itens — nada a faturar',
  PAYMENT_TYPE_UNAVAILABLE: 'Forma de pagamento não vinculada/habilitada na institution',
  TITLE_NOT_FOUND:     'Título financeiro não encontrado',
  BANK_NOT_FOUND:      'Banco/conta bancária inexistente',
  BANK_IN_USE:         'Banco do catálogo em uso por conta corrente de cliente — exclusão bloqueada',
  FINANCIAL_CONTRACT_EXISTS:        'Forma de pagamento já tem contrato financeiro (1 por forma)',
  FINANCIAL_CONTRACT_CASH_NO_TERMS: 'Contrato no caixa (conta 0) não aceita prazo nem taxa',
  PAYMENT_TYPE_NOT_LINKED:          'Forma de pagamento não vinculada à institution',
  AGREEMENT_NOT_FOUND:              'Carteira de cobrança não encontrada',
  AGREEMENT_INACTIVE:               'Carteira de cobrança inativa',
  TITLE_NOT_RECEIVABLE:             'Título a pagar — boleto só cobra recebíveis',
  TITLE_SETTLED:                    'Título já quitado',
  TITLE_HAS_OPEN_SLIP:              'Título já tem boleto vigente',
  BANK_SLIP_NOT_FOUND:              'Boleto não encontrado',
  BANK_SLIP_NO_TITLES:              'Boleto sem títulos',
  BANK_SLIP_DUPLICATE_TITLE:        'Título repetido no boleto',
  BANK_SLIP_MIXED_CUSTOMERS:        'Boleto agrupado só com títulos do mesmo cliente',
  BANK_SLIP_EXPIRATION_REQUIRED:    'Boleto agrupado exige vencimento informado',
  BANK_SLIP_INVALID_VALUE:          'Valor recebido inválido (0,01 a 99.999.999,99)',
  BANK_SLIP_NOT_OPEN:               'Boleto não está em aberto',
  BANK_SLIP_NOT_SETTLED:            'Boleto não está liquidado (ou já tem evento posterior)',
  BANK_SLIP_TITLE_REISSUED:         'Título do boleto já reemitido em outro boleto vigente',
  BANK_SLIP_BELOW_MINIMUM:          'Valor recebido abaixo do mínimo (face menos o desconto congelado)',
  NO_OPEN_CASHIER:                  'Nenhum caixa aberto',
  BANK_ACCOUNT_REQUIRED:            'Conta bancária obrigatória',
  CHECK_REQUIRED:                   'Informe ao menos um cheque',
  CHECK_SUM_MISMATCH:               'Soma dos cheques não confere com o valor da parcela',
  CHECK_NOT_FOUND:                  'Cheque não encontrado',
  CHECK_ALREADY_ACTIVE:             'Cheque já está em uso (identidade duplicada)',
  CHECK_NOT_IN_CUSTODY:             'Cheque não está em custódia',
  CHECK_NOT_DISCOUNTED:             'Cheque não está descontado na factoring',
  CHECK_NOT_RETURNABLE:             'Cheque não pode ser devolvido no estado atual',
  CHECK_NO_ORIGIN:                  'Cheque sem evento de recebimento — não é possível devolver',
  CHECK_ALREADY_MOVED:              'Cheque tem evento posterior — estorne o mais recente primeiro',
  CHECK_EVENT_NOT_FOUND:            'Evento do cheque não encontrado',
  CHECK_EVENT_NOT_REVERSIBLE:       'Este evento não pode ser estornado',
  CHECK_EXCEEDS_BALANCE:            'Valor do cheque excede o saldo aberto do título',
  CHECK_FACTORING_NOT_FOUND:        'Entidade da factoring inexistente',
  CHECK_IDENTITY_MISMATCH:          'Cheque já cadastrado com dados diferentes (valor/emitente/data)',
  REVERSAL_NOT_CURRENT: 'Só baixas vigentes (status N) podem ser estornadas',
  RATE_SUM_EXCEEDED:   'Soma dos percentuais de parceria passa de 90% (10% são da Setes)',
  REQUIRES_VALIDATION: 'Faturamento exige validação prévia (regra por item ausente/morta ou cadastro pendente)',
  ORDER_NO_BRANCH:     'Ordem sem ramo identificado (venda/compra/ajuste/serviço)',
  ORDER_NO_BILLING:    'Ordem sem condições de cobrança (forma/prazo) para gerar o financeiro',
  INVALID_JSON:        'Corpo da requisição não é um JSON válido',
  PAYLOAD_TOO_LARGE:   'Corpo da requisição excede o limite',
  ORDER_NOT_FOUND:     'Pedido não encontrado',
  INSTALLMENT_INVALID: 'Parcelamento inválido (parcelas 1..n contíguas, valores e datas válidos)',
  MAX_PARCELS_EXCEEDED: 'Número de parcelas passa do limite da forma de pagamento',
  ADJUST_PARAMS_REQUIRED: 'Ordem de ajuste exige CFOP no faturamento (sentido vem do ramo)',
  INVALID_DEADLINE:    'Prazo da negociação inválido para gerar parcelas',
  NEGATIVE_ITEM_VALUE: 'Item com valor líquido negativo (desconto maior que o total)',
  MISSING_NCM:         'Produto de mercadoria sem NCM no cadastro — faturamento bloqueado',
  INSTALLMENT_MISMATCH: 'Parcelamento elaborado difere do valor atual da ordem',
  RETURN_INVALID:      'Devolução inválida contra o pedido original (saldo/itens/valores/âncora)',
  RETURN_REQUIRES_ENTRY: 'Devolução de mercadoria exige ajuste de ENTRADA',
  ORIGIN_NOT_INVOICED: 'Pedido de venda de origem ainda não foi faturado',
  NOTHING_RETURNABLE:  'Pedido de origem sem saldo devolvível',
  INVOICE_NOT_FOUND:   'Nota fiscal não encontrada',
  INVOICE_NOT_CANCELLABLE: 'Nota não pode ser cancelada (pedido não faturado, nota já cancelada ou sincronizada da origem)',
  INVOICE_REASON_REQUIRED: 'Motivo do cancelamento é obrigatório',
  INVOICE_CANCEL_BLOCKED: 'Cancelamento bloqueado — resolva as pendências listadas antes (baixa, boleto liquidado, cheque que avançou, devolução)',
  PRIVILEGE_REQUIRED:  'Privilégio necessário para esta ação',
  RESOURCE_BUSY:       'Registro em uso por outra operação — tente novamente',
  TITLE_EXCEEDS_BALANCE: 'Valor da baixa passa do saldo em aberto do título',
  SERVICE_ORDER_CUSTOMER_OPEN: 'Cliente já tem uma ordem de serviço aberta',
  SERVICE_ORDER_OWN_ENDPOINT: 'Ordem de serviço fatura pelo módulo de OS',
  SERVICE_ORDER_ITEM_NOT_SERVICE: 'Item da ordem de serviço precisa ser um serviço',
  SERVICE_ORDER_ITEM_VALUE_REQUIRED: 'Item da ordem de serviço precisa de valor maior que zero',
}
